apiVersion: research.dynatrace.com/v1alpha1
kind: DeceptionAlertSink
metadata:
  name: deceptionalertsink-dynatrace
  namespace: koney-system
spec:
  dynatrace:
    secretName: dynatrace-api-token
    severity: HIGH
