// Copyright (c) 2025 Dynatrace LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package main

// ContainerMetadata represents container information
type ContainerMetadata struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// PodMetadata represents pod information
type PodMetadata struct {
	Name      string            `json:"name"`
	Namespace string            `json:"namespace"`
	Container ContainerMetadata `json:"container"`
}

// ProcessMetadata represents process information
type ProcessMetadata struct {
	PID       int    `json:"pid"`
	CWD       string `json:"cwd"`
	Binary    string `json:"binary"`
	Arguments string `json:"arguments"`
}

// TrapType represents the type of trap
type TrapType string

const (
	TrapTypeUnknown              TrapType = "unknown"
	TrapTypeFilesystemHoneytoken TrapType = "filesystem_honeytoken"
	TrapTypeHTTPEndpoint         TrapType = "http_endpoint"
	TrapTypeHTTPPayload          TrapType = "http_payload"
)

// KoneyAlert represents an alert generated by Koney
type KoneyAlert struct {
	Timestamp           string                 `json:"timestamp"`             // ISO 8601
	DeceptionPolicyName *string                `json:"deception_policy_name"` // Can be nil
	TrapType            TrapType               `json:"trap_type"`
	Metadata            map[string]interface{} `json:"metadata"`
	Pod                 *PodMetadata           `json:"pod"`     // Can be nil
	Process             *ProcessMetadata       `json:"process"` // Can be nil
}
